apiVersion: apps/v1
kind: Deployment
metadata:
 name: manual-shedule-deployment
spec:
 replicas: 3
 selector:
  matchLabels:
   app: nginx
 template:
  metadata:
   name: pod-creation.example.com
   labels:
    app: nginx
    type: front-end
  spec:
   nodeName: worker2
   containers:
   - name: nginx-container
     image: nginx:latest
     ports:
     - name: http
       containerPort: 80
