apiVersion: v1
kind: Pod
metadata:
 name: pod-creation.example.com
 labels:
  app: myapp1
  type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
  nodeSelector:
    size: "large"
