apiVersion: v1
kind: Pod
metadata:
 name: pod-creation.example.com
 labels:
  app: myapp1
  type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
  affinity:
   nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: size
         operator: In
         values:
         - extralarge
