apiVersion: v1
kind: ReplicationController
metadata:
 name: rc-demo.example.com
 labels:
  app: myapp2-rc-demo
  type: front-end
spec:
 replicas: 3
 template:
  metadata:
   name: rc-demo.example.com
   labels:
    app: myapp2
    type: front-end
  spec:
   containers:
   - name: nginx
     image: nginx:latest
